#!/usr/bin/env bash

set -ex

DRONE_BITBUCKET_CLIENT_ID=""
DRONE_BITBUCKET_CLIENT_SECRET=""
DRONE_RPC_SECRET=""
DRONE_SERVER_HOST=""
DRONE_SERVER_PROTO="https"

docker run \
  --volume=/var/lib/drone:/data \
  --env=DRONE_LOGS_TRACE=true\
  --env=DRONE_AGENTS_ENABLED=true \
  --env=DRONE_BITBUCKET_CLIENT_ID=${DRONE_BITBUCKET_CLIENT_ID} \
  --env=DRONE_BITBUCKET_CLIENT_SECRET=${DRONE_BITBUCKET_CLIENT_SECRET} \
  --env=DRONE_RPC_SECRET=${DRONE_RPC_SECRET} \
  --env=DRONE_SERVER_HOST=${DRONE_SERVER_HOST} \
  --env=DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO} \
  --env=DRONE_TLS_AUTOCERT=true \
